former.words <-
c("CEASED", "DECEASED", "EMERITUS", "END", "ENDED", "ENDING", 
"EX", "EXITED", "EXPIRE", "EXPIRED", "FORMER", "IMMED PAST", 
"IMMEDIATE", "IMMEDIATE PA", "IMMEDIATE PAST", "LEAVING", "LEFT", 
"OUTGOING", "PAST", "PREVIOUS", "PRIOR", "RESIGN", "RESIGNED", 
"RESIGNING", "RETIRED", "RETIRING", "ROLLED OFF", "TERM", "TERM END", 
"TERM ENDED", "TERM EXPIRED", "TERMINATED", "THR", "THROUGH", 
"THRU", "TIL", "UNT", "UNTIL")
