likely.titles <-
c("PRESIDENT", "CEO", "DIRECTOR\\b", "CHAIR", "TRUSTEE\\b", "TREASURER", 
"SECRETARY", "OFFICER", "COUNSEL", "FOUNDER", "PUBLISHER", "EDITOR\\b", 
"MEMBER\\b", "\\bCOO\\b", "CFO", "MANAGER", "\\bCTO\\b", "ADMINISTRATOR", 
"\\bCRO\\b", "CURATOR", "TEACHER", "CLERK", "CONTROLLER", "LIAISON", 
"INSTRUCTOR", "GENERAL", "COMPTROLLER", "HISTORIAN", "ADVISOR", 
"ARTISTIC", "KEEPER", "CHOREOGRAPHER", "EXECUTIVE\\s*$", "CHAPLAIN", 
"\\bCMO\\b", "WEBMASTER", "ASSISTANT\\s*$", "DEAN", "GOVERNOR", 
"SERGEANT", "\\bCAO\\b", "^\\bCHIEF\\b$", "WARDEN", "MASTER", 
"MATRON", "CONDUCTOR", "REPRESENTATIVE", "COORDINATOR", "ACCOUNTANT", 
"\\bEXECUTIVE BOARD\\b"
)
