likely.subjects <-
c("OPERATIONS", "FINANCE", "ADMINISTRATION", "MANAGEMENT", "EXHIBIT", 
"PUBLICITY", "ACTIVITIES", "BUILDING", "EDUCATION", "MARKETING", 
"STRATEGY", "SALES", "ENSHRINEMENT", "ADVANCEMENT", "FUNDRAISING", 
"COMMUNICATION", "PRODUCT", "CONSULTING", "TECHNOLOGY", "DEVELOPMENT", 
"GROUNDS", "\\bART", "MUSIC", "ENGINEERING", "BUSINESS", "DESIGN", 
"EXPERIENCE", "CULTURE", "\\bLAB", "AFFAIR", "BRANDING", "INTERNAL", 
"PUBLIC", "EXTERNAL", "PROMOTION", "HUMAN RESOURCES", "LEGAL", 
"RESEARCH", "TRANSPORTATION", "FELLOWSHIP", "FOUNDATION", "EVENT", 
"COLLECTION", "SCHOOL", "ASSOCIATION", "RADIO", "TV", "COMMITTEE", 
"MEMBERSHIP")
