###
### DEMO DATA
###

#' @name raw.titles
#' @docType data
#' @title Example titles. 
#'
#' @description A vector with examples of raw titles. 
NULL 

#' @name tinypartvii
#' @docType data
#' @title Sample of 10,000 orgs (~81,000 titles) as a Part VII data frame.
#'
#' @description A data frame of raw IRS 990 Part VII compensation records drawn
#'   from the 2023 NCCS efile release, in the current (modern) schema
#'   (`OBJECTID`, `EIN2`, `RETURN_TYPE`, `ORG_NAME_L1/L2`, `F9_07_COMP_DTK_*`).
#'   Ready to pipe into `standardize_df()`. Regenerated by
#'   `data-raw/make-tinypartvii.R`.
NULL

#' @name df.standard
#' @docType data
#' @title Title standardization crosswalk (variant to standard).
#'
#' @description A data frame mapping raw title variants to their canonical
#'   `title.standard` form. Snapshot of the `title-standardization` Google-Sheet
#'   tab; the live pipeline uses the pinned copy in `inst/extdata/crosswalks/`.
NULL

#' @name d.taxonomy
#' @docType data
#' @title Title taxonomy table.
#'
#' @description A data frame mapping each canonical `title.standard` to its
#'   taxonomy dimensions (domain, SOC codes, and role/hierarchy flags such as
#'   `ceo`, `c.level`, `board`). Snapshot of the `title-taxonomy` Google-Sheet tab.
NULL

#' @name status.mapping
#' @docType data
#' @title Status-code mapping table.
#'
#' @description A data frame mapping status-qualifier variants (e.g. "ACTING",
#'   "EMERITUS") to standardized status codes (e.g. "INTERIM", "FORMER") used in
#'   the `gen_status_codes()` step.
NULL

###
### DISAMBIGUATION DATA
###


#' @name date.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the `remove_dates` step to identify and remove dates from titles.   
NULL 

#' @name number.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the `gen_status_codes` step to remove numbers from titles.   
NULL 

#' @name likely.subjects
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the `fix_of()` function.  
NULL 

#' @name likely.titles
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the `standardize_conj` step with recognizing compound titles   
NULL 

#' @name possible.titles
#' @docType data
#' @title Helper data list.   
#'
#' @description Used in the `fix_of()` function  
NULL 

###
### STATUS CODES
###

#' @name former.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the gen_status_codes() step.   
NULL 

#' @name future.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the gen_status_codes() step.    
NULL 

#' @name interim.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the gen_status_codes() step.   
NULL 

#' @name regional.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the gen_status_codes() step.   
NULL 

#' @name possible.regional.list
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the gen_status_codes() step.    
NULL 
