###
### DEMO DATA
###

#' @name raw.titles
#' @docType data
#' @title Example titles. 
#'
#' @description A vector with examples of raw titles. 
NULL 

#' @name tinypartvii
#' @docType data
#' @title Sample of 10,000 orgs (~81,000 titles) as a Part VII data frame.
#'
#' @description A data frame of raw IRS 990 Part VII compensation records drawn
#'   from the 2023 NCCS efile release, in the current (modern) schema
#'   (`OBJECTID`, `EIN2`, `RETURN_TYPE`, `ORG_NAME_L1/L2`, `F9_07_COMP_DTK_*`).
#'   Ready to pipe into `standardize_df()`. Regenerated by
#'   `data-raw/make-tinypartvii.R`.
NULL

###
### CROSSWALKS
###
### Built from the CSV tables in data-raw/crosswalks/ by
### data-raw/crosswalks/build-crosswalks.R. Edit the CSVs, not these objects.

#' @name title.xwalk
#' @docType data
#' @title Title-standardization crosswalk (variant to standard).
#'
#' @description Maps each cleaned title variant (`title.variant`, matched to
#'   `TitleTxt7`) to its standard form (`title.standard`), with an optional
#'   board sub-role in `strata` / `strata.label`. Used by
#'   `standardize_titles()`; load it with [get_title_xwalk()].
#'
#' @format A data frame of character columns: `title.variant`,
#'   `title.standard`, `strata`, `strata.label`.
#' @source `data-raw/crosswalks/title-standardization.csv`, started from the
#'   title-taxonomy-map Google Sheet (retired 2026-10-08).
NULL

#' @name title.patterns
#' @docType data
#' @title Head rules for titles the crosswalk does not list.
#'
#' @description Learned from the crosswalk by
#'   `data-raw/partvii-validation/10-pattern-rules.R`. A head is a crosswalk
#'   variant at the end (`position` "suffix") or start ("prefix") of a title.
#'   Each rule maps titles with that longest head to `title.standard`: either
#'   the standard most known titles with that head map to (`rule` "majority")
#'   or the head's own standard when those titles share its role level
#'   ("level"). `support` is the number of known titles behind the rule and
#'   `precision` the share of them it gets right. Used by
#'   `standardize_titles()` through [match_title_patterns()]; load it with
#'   [get_title_patterns()].
#'
#' @format A data frame: `position`, `head`, `title.standard`, `rule`
#'   (character), `support` (integer), `precision` (numeric).
#' @source `data-raw/crosswalks/title-patterns.csv`.
NULL

#' @name title.taxonomy
#' @docType data
#' @title Title taxonomy (standard title to domain, SOC code, and role).
#'
#' @description Maps each `title.standard` to its functional domain, its 2018
#'   SOC occupation codes, and its role: an employee level or a board role.
#'   Used by `categorize_titles()`; load it with [get_title_taxonomy()].
#'
#'   The employee levels are:
#'   - `CEO`: the top staff job (CEO, executive director).
#'   - `OFFICER`: C-suite, vice presidents, deputies.
#'   - `MANAGER`: directors of departments, managers.
#'   - `PROFESSIONAL`: non-managerial jobs often reported for their pay, such
#'     as physicians, lawyers, professors and coaches.
#'   - `STAFF`: everything else.
#'
#'   The level comes from the title alone. Whether a person was a key or
#'   highly compensated employee in a filing comes from the checkboxes and pay.
#'
#' @format A data frame of character columns, one row per `title.standard`:
#'   \describe{
#'     \item{title.standard}{standard title, the key matched by `standardize_titles()`}
#'     \item{domain.category, domain.label}{functional domain, a pair from the
#'       controlled vocabulary in `data-raw/crosswalks/domains.csv`: executive
#'       (general management), governance (board), operations (a support
#'       function), industry-specific (the organization's field), or non-job
#'       title}
#'     \item{soc.label, major.group, minor.group, broad.group, detailed.occupation}{2018 SOC
#'       codes; `soc.label` is the official title of the most detailed code}
#'     \item{emp.level}{`CEO`, `OFFICER`, `MANAGER`, `PROFESSIONAL`, `STAFF`, or blank}
#'     \item{board.role}{`CHAIR`, `VICE CHAIR`, `SECRETARY`, `TREASURER`, `MEMBER`, or
#'       blank. Board titles use five standards, BOARD PRESIDENT (`CHAIR`)
#'       through BOARD MEMBER.}
#'     \item{emp, ceo, c.level, dir.vp, mgr, spec, board, pres, vp, sec, treas, mem}{legacy
#'       role flags (`"X"` or blank), derived from `emp.level` and `board.role`:
#'       `c.level` is CEO or OFFICER, `spec` is PROFESSIONAL or STAFF, `pres`
#'       is CHAIR, `vp` is VICE CHAIR, `mem` is MEMBER. `dir.vp` is retired
#'       and always blank.}
#'   }
#' @source `data-raw/crosswalks/title-taxonomy.csv`, started from the
#'   title-taxonomy-map Google Sheet (retired 2026-10-08).
NULL

#' @name status.codes
#' @docType data
#' @title Status-code crosswalk.
#'
#' @description Maps status-qualifier variants (e.g. "ACTING", "EMERITUS") to
#'   standardized status codes (e.g. "INTERIM", "FORMER"). Used by
#'   `gen_status_codes()`; load it with [get_status_codes()].
#'
#' @format A data frame of character columns: `status.variant`,
#'   `status.qualifier`.
#' @source `data-raw/crosswalks/status-codes.csv`, started from the
#'   title-taxonomy-map Google Sheet (retired 2026-10-08).
NULL

###
### DISAMBIGUATION DATA
###


#' @name date.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the `remove_dates` step to identify and remove dates from titles.   
NULL 

#' @name number.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the `gen_status_codes` step to remove numbers from titles.   
NULL 

#' @name likely.subjects
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the `fix_of()` function.  
NULL 

#' @name likely.titles
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the `standardize_conj` step with recognizing compound titles   
NULL 

#' @name possible.titles
#' @docType data
#' @title Helper data list.   
#'
#' @description Used in the `fix_of()` function  
NULL 

###
### STATUS CODES
###

#' @name former.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the gen_status_codes() step.   
NULL 

#' @name future.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the gen_status_codes() step.    
NULL 

#' @name interim.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the gen_status_codes() step.   
NULL 

#' @name regional.words
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the gen_status_codes() step.   
NULL 

#' @name possible.regional.list
#' @docType data
#' @title Helper data list.  
#'
#' @description Used in the gen_status_codes() step.    
NULL 
